# .travis.yml

# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.2
language: objective-c
cache: cocoapods
before_install:
- export LANG=en_US.UTF-8
- env
- locale
- curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.9.4/Carthage.pkg"
- sudo installer -pkg "Carthage.pkg" -target /
- rm "Carthage.pkg"
- cd XCode; carthage update --platform osx 
script:
- cd XCode; set -o pipefail && xcodebuild test -project SwiftDate -scheme SwiftDateTests -configuration Debug -destination "platform=OSX" ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES | xcpretty -c
- swiftlint
- pod lib lint
